### ISSUE TITLE
Fix UI and text editor scaling with small window widths

### ISSUE THREAD

**Issue by PWhiddy** [shader-park/shader-park-website#5]

**Comment by torinmb** [comment]
@PWhiddy can we close this now that most of the buttons are moved to the action bar now?

**Comment by PWhiddy** [comment]
Yes I'm fine with that. 
Should we disable opening the code on mobile though? It looks like this 
![Uploading 94505510...]

**Comment by torinmb** [comment]
haha it looks beautiful
