### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by torinmb** [shader-park/shader-park-website#78]
Background on us and what lead to the project. 
Shout out to Michael during the early prototype that planted a seed for the project.

People who helped in the process + research we used:
Huge thank you to IQ -> link to his site + SDF research.

Running list of thankyous for people that reviewed the project:
IQ, Recardo, Ben, Casey, Kyle, Reza.

Include info on tools:
Three.js, Vue.js, Codemirror, polymer, firebase.

**Comment by PWhiddy** [comment]
Putting info about our tools like what database we're using seems unnecessary for the about page

**Comment by torinmb** [comment]
we have an about page. we did it
