### ISSUE TITLE
saving with syntax errors causes page to crash without displaying editor

### ISSUE THREAD

**Issue by PWhiddy** [shader-park/shader-park-website#82]

**Comment by PWhiddy** [comment]
use esprima validate

**Comment by torinmb** [comment]
@PWhiddy 
One thing I'd love to work out is how to prevent the Glsl sculpture from disappearing when you type a line of code that doesn't match. This works fine on the js mode.
I tried putting a try / catch around the glslToThreeJSMaterial, but it seems to be throwing an error inside shader-park-core. I think we need to set up the GLSL errors to be passed along the same way as the js errors.
Could be worth opening this up as a separate issue

https://github.com/shader-park/shader-park-website/blob/6719d6661954b5ff477fe8c803c1b8af74a11d61/src/threejs-sculpture/SculptureN.js#L84

**Comment by PWhiddy** [comment]
@torinmb 
Webgl doesn't throw normal javascript exceptions for shader compile errors. iirc threejs doesn't try to compile shaders until the moment they need to be rendered, so we'd need to explicitly ask it to try compiling the shader directly and act on that result.
Here's where threejs checks compile status
https://github.com/mrdoob/three.js/blob/1bc34d662c4fc58df7a210c61d071d17b0177d9b/src/renderers/webgl/WebGLProgram.js#L55

**Comment by torinmb** [comment]
Would it make sense to make our own webgl context and compile the shader to check for errors? If we did that at line 84 we could also get glsl errors in our console

**Comment by PWhiddy** [comment]
The ideal scenario would be to compile the shaders without having to go through threejs at all, which is 99% dead weight for our use case. But even when using threejs we dont need a separate webgl context, I think threejs' material api will allow us to request shader compilation and errors. And even if we want to do it separately, we can still share a context with threejs theres no reason for a separate context.
