### ISSUE TITLE
Make /embed use a transparent background

### ISSUE THREAD

**Issue by torinmb** [shader-park/shader-park-website#90]

**Comment by torinmb** [comment]
![image](https://user-images.githubusercontent.com/6014011/94720000-e5d9ea80-0321-11eb-8ce1-4ebf4987515e.png)
cfede2026ecb09e364f74dec5a6f5760ebda55b5
53f985193ae32e1ab833d8fd44712c9a59fa8847
it works :)

now we just need the ability to set the environment light

**Comment by torinmb** [comment]
Is there any way to pass an image in as our environment map? It'd be so cool to be able to capture an image of the DOM and then pass it in as the environment. We could use something like https://github.com/tsayen/dom-to-image (not sure how performant it is) @PWhiddy

**Comment by PWhiddy** [comment]
Yess I'm so excited about this one!

**Comment by PWhiddy** [comment]
> Is there any way to pass an image in as our environment map? It'd be so cool to be able to capture an image of the DOM and then pass it in as the environment. We could use something like https://github.com/tsayen/dom-to-image (not sure how performant it is) @PWhiddy

Something like that might work. We could have a texture type input which images could be sent into. I doubt that method would run with reasonable framerate, but we'd have to test to know

**Comment by PWhiddy** [comment]
Something I was thinking about, if we currently have a default of a transparent shader with white css background on the website then things will look weird when you change the background color and the background stays white. Either transparent or opaque background each has its advantages/disadvantages, but it definitely will be good to change that mode either through api or ui.

**Comment by torinmb** [comment]
We should just create inputVec2, inputVec3, and inputVec4 so that way we can call ```setBackgroundColor(vec4(1, 0, 1, 1));``` , or we could pass in a uniform. This would allow us to be able to live update the background color by sampling the DOM. 
Imagine you embed the sculpture at a fixed position on the site and as you scroll down the page you want the sculpture's background color to match the same as the website background color.

Right now if you want to modify a uniform in real-time you can do it through window.guiParams, so we can use that to update the new input vec4. eg:
```
let backgroundCol = convertHexToNormalizedColor(document.body.style.backgoundColor); // assuming this turns the color to vec4
let color = inputVec4(backgroundCol); //creates a uniform
window.addEventListener('scroll', () => {
    window.guiParams.color = convertHexToNormalizedColor(document.body.style.backgoundColor);
});
```

We could easily make GUI controls for a vec3 and vec4 as a color picker in Dat.GUI. I just wish there was an XY slider for vec2s.
